name: Project CI/CD

on:
  push:
    branches: [ "develop", "main" ]

jobs:
  version:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Generate version
        run: |
          git pull origin $GITHUB_REF
          touch build.env
          chmod +x cicd/gen-version.sh
          VERSION=$(bash cicd/gen-version.sh | tr -d '\n')
          echo "$GITHUB_REF - $VERSION"
          if [[ "${VERSION:0:1}" != "v" ]]; then
            echo "Cannot generate version, result: $VERSION"
            exit 1
          fi
          echo "VERSION=$VERSION" > build.env
          echo "$GITHUB_REF - $VERSION"

      - name: Publish version tag
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
        run: |
          VERSION=$(cat build.env | cut -d '=' -f2)
          git tag $VERSION
          git push origin $VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
