name: Project CI/CD

on:
  push:
    branches: [ "develop", "main" ]

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Generate version
        run: |
          touch build.env
          chmod +x cicd/gen-version.sh
          VERSION=$(bash cicd/gen-version.sh | tr -d '\n')
          echo "$GITHUB_REF - $VERSION"
          if [[ "${VERSION:0:1}" != "v" ]]; then
            echo "Cannot generate version, result: $VERSION"
            exit 1
          fi
          echo "VERSION=$VERSION" >> build.env
          echo "$GITHUB_REF - $VERSION"

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Set up authentication
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Publish version tag
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
        run: |
          git tag $VERSION
          git push origin $VERSION
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
